--Localization.enUS.lua

IlarosNaviLocals = {
}

-- Chat notifications
MAPCOORDS_HWorld	= "Now hiding all coords on worldmap"
MAPCOORDS_SWorld	= "Now showing all coords on worldmap"
MAPCOORDS_HCursor	= "Now hiding cursor coords on worldmap"
MAPCOORDS_SCursor	= "Now showing cursor coords on worldmap"
MAPCOORDS_HWPlayer	= "Now hiding player coords on worldmap"
MAPCOORDS_SWPlayer	= "Now showing player coords on worldmap"
MAPCOORDS_HPortrait	= "Now hiding all portrait coords"
MAPCOORDS_SPortrait	= "Now showing all portrait coords"
MAPCOORDS_HPlayer	= "Now hiding player portrait coords"
MAPCOORDS_SPlayer	= "Now showing player portrait coords"
MAPCOORDS_HAParty	= "Now hiding all party members portrait coords"
MAPCOORDS_SAParty	= "Now showing all party members portrait coords"
MAPCOORDS_HParty1	= "Now hiding your first party member portrait coords"
MAPCOORDS_SParty1	= "Now showing your first party member portrait coords"
MAPCOORDS_HParty2	= "Now hiding your second party member portrait coords"
MAPCOORDS_SParty2	= "Now showing your second party member portrait coords"
MAPCOORDS_HParty3	= "Now hiding your third party member portrait coords"
MAPCOORDS_SParty3	= "Now showing your third party member portrait coords"
MAPCOORDS_HParty4	= "Now hiding your fourth party member portrait coords"
MAPCOORDS_SParty4	= "Now showing your fourth party member portrait coords"

-- Slash information
MAPCOORDS_SLASH1	= "|cffff38ffIlarosNavi Commands:|r"
MAPCOORDS_SLASH2	= "-- Worldmap Coords --"
MAPCOORDS_SLASH3	= "-- Portrait Coords --"
MAPCOORDS_SLASH4	= "Cursor: "
MAPCOORDS_SLASH5	= "Player: "
MAPCOORDS_SLASH6	= "-- Waypoints --"

MAPCOORDS_WMON		= "|cffff78ff/Navi a|r - Toggles display of all coords on the worldmap"
MAPCOORDS_WMOFF		= "|cffff78ff/Navi a|r - Toggles display of all coords on the worldmap"
MAPCOORDS_WMCON		= "|cffff78ff/Navi c|r - Toggles display of cursor coords on the worldmap"
MAPCOORDS_WMCOFF	= "|cffff78ff/Navi c|r - Toggles display of cursor coords on the worldmap"
MAPCOORDS_WMPON		= "|cffff78ff/Navi s|r - Toggles display of player coords on the worldmap"
MAPCOORDS_WMPOFF	= "|cffff78ff/Navi s|r - Toggles display of player coords on the worldmap"
MAPCOORDS_APON		= "|cff78ffff/Navi p|r - Toggles display of all portrait coords"
MAPCOORDS_APOFF		= "|cff78ffff/Navi p|r - Toggles display of all portrait coords"
MAPCOORDS_YPON		= "|cff78ffff/Navi p0|r - Toggles display of your portrait coords"
MAPCOORDS_YPOFF		= "|cff78ffff/Navi p0|r - Toggles display of your portrait coords"
MAPCOORDS_APMON		= "|cff78ffff/Navi g|r - Toggles display of your all your party members portrait coords"
MAPCOORDS_APMOFF	= "|cff78ffff/Navi g|r - Toggles display of your all your party members portrait coords"
MAPCOORDS_P1ON		= "|cff78ffff/Navi p1|r - Toggles display of your first party member portrait coords"
MAPCOORDS_P1OFF		= "|cff78ffff/Navi p1|r - Toggles display of your first party member portrait coords"
MAPCOORDS_P2ON		= "|cff78ffff/Navi p2|r - Toggles display of your second party member portrait coords"
MAPCOORDS_P2OFF		= "|cff78ffff/Navi p2|r - Toggles display of your second party member portrait coords"
MAPCOORDS_P3ON		= "|cff78ffff/Navi p3|r - Toggles display of your third party member portrait coords"
MAPCOORDS_P3OFF		= "|cff78ffff/Navi p3|r - Toggles display of your third party member portrait coords"
MAPCOORDS_P4ON		= "|cff78ffff/Navi p4|r - Toggles display of your fourth party member portrait coords"
MAPCOORDS_P4OFF		= "|cff78ffff/Navi p4|r - Toggles display of your fourth party member portrait coords"
MAPCOORDS_ABOUT		= "/Navi v - Version info"
MAPCOORDS_WAY1      = "|cffffff78/Navi n|r - Direct waypoint arrow to the next waypoint"
MAPCOORDS_WAY2      = "|cffffff78/Navi h|r - Add waypoint at current position"
MAPCOORDS_WAY3      = "|cffffff78/Navi [zone] <x> <y> [name]|r - Add a waypoint at x,y in zone 'zone' with name 'name', zone and name are optional"
MAPCOORDS_WAY4      = "|cffffff78/Navi reset all|r - Reset all waypoints"
MAPCOORDS_WAY5      = "|cffffff78/Navi reset <zone>|r - Reset all waypoints in zone 'zone'"

-- Option texts
MAPCOORDS_WMOP		= "Worldmap Coords:"
MAPCOORDS_WMOP1		= "Show Player Coords on Worldmap"
MAPCOORDS_WMOP2		= "Show Cursor Coords on Worldmap"
MAPCOORDS_PTOP		= "Portrait Coords:"
MAPCOORDS_PTP		= "Show Coords under Player Portrait"
MAPCOORDS_PTG1		= "Show Coords for Group Member 1"
MAPCOORDS_PTG2		= "Show Coords for Group Member 2"
MAPCOORDS_PTG3		= "Show Coords for Group Member 3"
MAPCOORDS_PTG4		= "Show Coords for Group Member 4"
MAPCOORDS_MOP		= "Accuracy:"
MAPCOORDS_SDCD		= "Use Decimals in Coords Display (Not for Coordinate Block)"
MAPCOORDS_HINT      = "Enter in chat:\n\n|cffffff78/Navi|r for Slash Commands\n|cffffff78/NaviO|r for this Option Window"

setmetatable(IlarosNaviLocals, {__index=function(t,k) rawset(t, k, k); return k; end})
