-- English, the default

MAPCOORDS_VERSION 	= "0.7"

-- Chat notifications
MAPCOORDS_HWorld	= "Now hiding all coords on worldmap"
MAPCOORDS_SWorld	= "Now showing all coords on worldmap"
MAPCOORDS_HCursor	= "Now hiding cursor coords on worldmap"
MAPCOORDS_SCursor	= "Now showing cursor coords on worldmap"
MAPCOORDS_HWPlayer	= "Now hiding player coords on worldmap"
MAPCOORDS_SWPlayer	= "Now showing player coords on worldmap"
MAPCOORDS_HPortrait	= "Now hiding all portrait coords"
MAPCOORDS_SPortrait	= "Now showing all portrait coords"
MAPCOORDS_HPlayer	= "Now hiding player portrait coords"
MAPCOORDS_SPlayer	= "Now showing player portrait coords"
MAPCOORDS_HAParty	= "Now hiding all party members portrait coords"
MAPCOORDS_SAParty	= "Now showing all party members portrait coords"
MAPCOORDS_HParty1	= "Now hiding your first party member portrait coords"
MAPCOORDS_SParty1	= "Now showing your first party member portrait coords"
MAPCOORDS_HParty2	= "Now hiding your second party member portrait coords"
MAPCOORDS_SParty2	= "Now showing your second party member portrait coords"
MAPCOORDS_HParty3	= "Now hiding your third party member portrait coords"
MAPCOORDS_SParty3	= "Now showing your third party member portrait coords"
MAPCOORDS_HParty4	= "Now hiding your fourth party member portrait coords"
MAPCOORDS_SParty4	= "Now showing your fourth party member portrait coords"

-- Slash information
MAPCOORDS_SLASH1	= "|cffff38ffIlarosNavi Commands:|r"
MAPCOORDS_SLASH2	= "-- Worldmap Coords --"
MAPCOORDS_SLASH3	= "-- Portrait Coords --"
MAPCOORDS_SLASH4	= "Cursor: "
MAPCOORDS_SLASH5	= "Player: "
MAPCOORDS_SLASH6	= "-- Waypoints --"

MAPCOORDS_WMON		= "|cffff78ff/Navi a|r - Toggles display of all coords on the worldmap"
MAPCOORDS_WMOFF		= "|cffff78ff/Navi a|r - Toggles display of all coords on the worldmap"
MAPCOORDS_WMCON		= "|cffff78ff/Navi c|r - Toggles display of cursor coords on the worldmap"
MAPCOORDS_WMCOFF	= "|cffff78ff/Navi c|r - Toggles display of cursor coords on the worldmap"
MAPCOORDS_WMPON		= "|cffff78ff/Navi s|r - Toggles display of player coords on the worldmap"
MAPCOORDS_WMPOFF	= "|cffff78ff/Navi s|r - Toggles display of player coords on the worldmap"
MAPCOORDS_APON		= "|cff78ffff/Navi p|r - Toggles display of all portrait coords"
MAPCOORDS_APOFF		= "|cff78ffff/Navi p|r - Toggles display of all portrait coords"
MAPCOORDS_YPON		= "|cff78ffff/Navi p0|r - Toggles display of your portrait coords"
MAPCOORDS_YPOFF		= "|cff78ffff/Navi p0|r - Toggles display of your portrait coords"
MAPCOORDS_APMON		= "|cff78ffff/Navi g|r - Toggles display of your all your party members portrait coords"
MAPCOORDS_APMOFF	= "|cff78ffff/Navi g|r - Toggles display of your all your party members portrait coords"
MAPCOORDS_P1ON		= "|cff78ffff/Navi p1|r - Toggles display of your first party member portrait coords"
MAPCOORDS_P1OFF		= "|cff78ffff/Navi p1|r - Toggles display of your first party member portrait coords"
MAPCOORDS_P2ON		= "|cff78ffff/Navi p2|r - Toggles display of your second party member portrait coords"
MAPCOORDS_P2OFF		= "|cff78ffff/Navi p2|r - Toggles display of your second party member portrait coords"
MAPCOORDS_P3ON		= "|cff78ffff/Navi p3|r - Toggles display of your third party member portrait coords"
MAPCOORDS_P3OFF		= "|cff78ffff/Navi p3|r - Toggles display of your third party member portrait coords"
MAPCOORDS_P4ON		= "|cff78ffff/Navi p4|r - Toggles display of your fourth party member portrait coords"
MAPCOORDS_P4OFF		= "|cff78ffff/Navi p4|r - Toggles display of your fourth party member portrait coords"
MAPCOORDS_ABOUT		= "/Navi v - Version info"
MAPCOORDS_WAY1      = "|cffffff78/Navi n|r - Direct waypoint arrow to the next waypoint"
MAPCOORDS_WAY2      = "|cffffff78/Navi h|r - Add waypoint at current position"
MAPCOORDS_WAY3      = "|cffffff78/Navi [zone] <x> <y> [name]|r - Add a waypoint at x,y in zone 'zone' with name 'name', zone and name are optional"
MAPCOORDS_WAY4      = "|cffffff78/Navi reset all|r - Reset all waypoints"
MAPCOORDS_WAY5      = "|cffffff78/Navi reset <zone>|r - Reset all waypoints in zone 'zone'"

-- Option texts
MAPCOORDS_WMOP		= "Worldmap Coords:"
MAPCOORDS_WMOP1		= "Show Player Coords on Worldmap"
MAPCOORDS_WMOP2		= "Show Cursor Coords on Worldmap"
MAPCOORDS_PTOP		= "Portrait Coords:"
MAPCOORDS_PTP		= "Show Coords under Player Portrait"
MAPCOORDS_PTG1		= "Show Coords for Group Member 1"
MAPCOORDS_PTG2		= "Show Coords for Group Member 2"
MAPCOORDS_PTG3		= "Show Coords for Group Member 3"
MAPCOORDS_PTG4		= "Show Coords for Group Member 4"
MAPCOORDS_MOP		= "Accuracy:"
MAPCOORDS_SDCD		= "Use Decimals in Coords Display (Not for Coordinate Block)"
MAPCOORDS_HINT      = "Enter in chat:\n\n|cffffff78/Navi|r for Slash Commands\n|cffffff78/NaviO|r for this Option Window"

-- German
if (GetLocale() == "deDE") then

-- Chat notifications
MAPCOORDS_HWorld	= "Alle Weltkartenkoordinaten wurden ausgeblendet."
MAPCOORDS_SWorld	= "Alle Weltkartenkoordinaten wurden eingeblendet."
MAPCOORDS_HCursor	= "Cursorkoordinaten auf der Weltkarte wurden ausgeblendet."
MAPCOORDS_SCursor	= "Cursorkoordinaten auf der Weltkarte wurden eingeblendet."
MAPCOORDS_HWPlayer	= "Spielerkoordinaten auf der Weltkarte wurden ausgeblendet."
MAPCOORDS_SWPlayer	= "Spielerkoordinaten auf der Weltkarte wurden eingeblendet."
MAPCOORDS_HPortrait	= "Alle Portraitkoordinaten wurden ausgeblendet."
MAPCOORDS_SPortrait	= "Alle Portraitkoordinaten wurden eingeblendet."
MAPCOORDS_HPlayer	= "Spielerkoordinaten wurden ausgeblendet."
MAPCOORDS_SPlayer	= "Spielerkoordinaten wurden eingeblendet."
MAPCOORDS_HAParty	= "Alle Gruppenkoordinaten wurden ausgeblendet."
MAPCOORDS_SAParty	= "Alle Gruppenkoordinaten wurden eingeblendet."
MAPCOORDS_HParty1	= "Erste Gruppenkoordinaten wurden ausgeblendet."
MAPCOORDS_SParty1	= "Erste Gruppenkoordinaten wurden eingeblendet."
MAPCOORDS_HParty2	= "Zweite Gruppenkoordinaten wurden ausgeblendet."
MAPCOORDS_SParty2	= "Zweite Gruppenkoordinaten wurden eingeblendet."
MAPCOORDS_HParty3	= "Dritte Gruppenkoordinaten wurden ausgeblendet."
MAPCOORDS_SParty3	= "Dritte Gruppenkoordinaten wurden eingeblendet."
MAPCOORDS_HParty4	= "Vierte Gruppenkoordinaten wurden ausgeblendet."
MAPCOORDS_SParty4	= "Vierte Gruppenkoordinaten wurden eingeblendet."

-- Slash information
MAPCOORDS_SLASH1	= "|cffff38ffIlarosNavi-Kommandos:|r"
MAPCOORDS_SLASH2	= "-- Weltkartenkoordinaten --"
MAPCOORDS_SLASH3	= "-- Portraitkoordinaten --"
MAPCOORDS_SLASH4	= "Cursor: "
MAPCOORDS_SLASH5	= "Spieler: "
MAPCOORDS_SLASH6	= "-- Wegpunkte --"

MAPCOORDS_WMON		= "|cffff78ff/Navi a|r - Alle Koordinaten auf der Weltkarte aus"
MAPCOORDS_WMOFF		= "|cffff78ff/Navi a|r - Alle Koordinaten auf der Weltkarte ein"
MAPCOORDS_WMCON		= "|cffff78ff/Navi c|r - Cursorkoordinaten auf der Weltkarte aus"
MAPCOORDS_WMCOFF	= "|cffff78ff/Navi c|r - Cursorkoordinaten auf der Weltkarte ein"
MAPCOORDS_WMPON		= "|cffff78ff/Navi s|r - Spielerkoordinaten auf der Weltkarte aus"
MAPCOORDS_WMPOFF	= "|cffff78ff/Navi s|r -- Spielerkoordinaten auf der Weltkarte ein"
MAPCOORDS_APON		= "|cff78ffff/Navi p|r - alle Portraitkoordinaten aus"
MAPCOORDS_APOFF		= "|cff78ffff/Navi p|r - alle Portraitkoordinaten ein"
MAPCOORDS_YPON		= "|cff78ffff/Navi p0|r - alle Spielerkoordinaten aus"
MAPCOORDS_YPOFF		= "|cff78ffff/Navi p0|r - alle Spielerkoordinaten ein"
MAPCOORDS_APMON		= "|cff78ffff/Navi g|r - alle Gruppen-Portrait-Koordinaten aus"
MAPCOORDS_APMOFF	= "|cff78ffff/Navi g|r - alle Gruppen-Portrait-Koordinaten ein"
MAPCOORDS_P1ON		= "|cff78ffff/Navi p1|r - erste Gruppenkoordinaten aus"
MAPCOORDS_P1OFF		= "|cff78ffff/Navi p1|r - erste Gruppenkoordinaten ein"
MAPCOORDS_P2ON		= "|cff78ffff/Navi p2|r - zweite Gruppenkoordinaten aus"
MAPCOORDS_P2OFF		= "|cff78ffff/Navi p2|r - zweite Gruppenkoordinaten ein"
MAPCOORDS_P3ON		= "|cff78ffff/Navi p3|r - dritte Gruppenkoordinaten aus"
MAPCOORDS_P3OFF		= "|cff78ffff/Navi p3|r - dritte Gruppenkoordinaten ein"
MAPCOORDS_P4ON		= "|cff78ffff/Navi p4|r - vierte Gruppenkoordinaten aus"
MAPCOORDS_P4OFF		= "|cff78ffff/Navi p4|r - vierte Gruppenkoordinaten ein"
MAPCOORDS_ABOUT		= "/Navi v -- Versionsinformation"
MAPCOORDS_WAY1      = "|cffffff78/Navi n|r - Zielpfeil auf n\195\164chsten Zielpunkt richten"
MAPCOORDS_WAY2      = "|cffffff78/Navi h|r - Zielpunkt am aktuellen Ort setzen"
MAPCOORDS_WAY3      = "|cffffff78/Navi [zone] <x> <y> [name]|r - Zielpunkt bei x,y in Zone 'zone' mit Name 'name' setzen, Zone und Name sind optional"
MAPCOORDS_WAY4      = "|cffffff78/Navi reset all|r - alle Zielpunkte l\195\182schen"
MAPCOORDS_WAY5      = "|cffffff78/Navi reset <zone>|r - alle Zielpunkte in Zone 'zone' l\195\182schen"

-- Option texts
MAPCOORDS_WMOP		= "Weltkarten-Koordinaten:"
MAPCOORDS_WMOP1		= "Spielerkoordinaten anzeigen"
MAPCOORDS_WMOP2		= "Cursoroordinaten anzeigen"
MAPCOORDS_PTOP		= "Portraitkoordinaten:"
MAPCOORDS_PTP		= "Koordinaten unter Spielerportrait anzeigen"
MAPCOORDS_PTG1		= "Koordinaten f\195\188r Gruppenmitglied 1 anzeigen"
MAPCOORDS_PTG2		= "Koordinaten f\195\188r Gruppenmitglied 2 anzeigen"
MAPCOORDS_PTG3		= "Koordinaten f\195\188r Gruppenmitglied 3 anzeigen"
MAPCOORDS_PTG4		= "Koordinaten f\195\188r Gruppenmitglied 4 anzeigen"
MAPCOORDS_MOP		= "Genauigkeit:"
MAPCOORDS_SDCD		= "Dezimalen der Koordinaten (gilt nicht f\195\188r Koordinatenbox)"
MAPCOORDS_HINT      = "Im Chat eingeben:\n\n|cffffff78/Navi|r f\195\188r Slashkommandos\n|cffffff78/NaviO|r f\195\188r dieses Optionsfenster"

end